pipeline:
  security-check:
    image: volunteerliveteam/drone-security-check
    environment:
      - REPO_NAME=${DRONE_REPO_NAME}
      - REPO_OWNER=${DRONE_REPO_OWNER}
      - PULL_REQUEST=${DRONE_PR_NUMBER}
      - TRUSTED_USERS=markspolakovs,pironic
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t vlt/marconi:drone-${DRONE_BUILD_NUMBER} .
  rancher:
    image: peloton/drone-rancher
    service: marconi/${DRONE_BRANCH}
    docker_image: vlt/marconi:drone-${DRONE_BUILD_NUMBER}
    confirm: true
    timeout: 300
    secrets: [ plugin_url, rancher_access_key, rancher_secret_key ]
    when:
      branch: [dev, master]
      event: [ push, tag, deployment ]
  slack:
    image: plugins/slack
    channel: technical
    secrets: [ slack_webhook ]
