pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t vlt/marconi:drone-${DRONE_BUILD_NUMBER} .
  rancher:
    image: peloton/drone-rancher
    service: marconi/vlt
    docker_image: vlt/marconi:drone-${DRONE_BUILD_NUMBER}
    confirm: true
    timeout: 300
    secrets: [ plugin_url, rancher_access_key, rancher_secret_key ]
    when:
      event: [push, tag, deployment]
