reddit:
  userAgent: USER_AGENT
  clientId: REDDIT_CLIENT_ID
  clientSecret: REDDIT_CLIENT_SECRET
  refreshToken: REDDIT_REFRESH_TOKEN
  username: REDDIT_USERNAME
  password: REDDIT_PASSWORD

influx:
  host: INFLUX_HOST
  database: INFLUX_DATABASE
  measurements:
    posts: INFLUX_MEASUREMENT_POSTS
    viewers: INFLUX_MEASUREMENT_VIEWERS

database:
  type: INFLUX_DATABASE_TYPE
  path: INFLUX_DATABASE_PATH