reddit:
  userAgent: 'vlt team bot (by /u/youlikethaaaat)'

influx:
  #host:
  database: reddit
  measurements:
    posts: posts
    viewers: viewers

database:
  type: lowdb
  path: ./config/database.json